### ISSUE TITLE
Pass on GET request arguments

### ISSUE THREAD

**Issue by beleon** [sellleon/mimime#5]
Currently get arguments of the specified target URL are not getting passed on.

**Comment by FChris** [comment]
Can you describe in more detail where and what that means? 
Do you have an idea already where in the code this bug occurs?

**Comment by beleon** [comment]
When requesting an image with a URL that contains a GET request, e.g. http://example.com/example?q=42, mimime will cut off the GET request `?q=42`. I suspect that the GET request is parsed by the go http library and removed from the `URL.Path`.
